import type { NextPage } from "next"
import Head from "next/head"
// import { serverSideTranslations } from "next-i18next/serverSideTranslations"
// import { defaultLocale } from "~/locales/config"
// import { useTranslation } from "next-i18next"

// import { Typography, Button } from "UI"
// import { IconWhatsApp } from "UI/Icons"

const Home: NextPage = () => {
  // const { t } = useTranslation("common")

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

// export const getStaticProps: GetStaticProps = async ({ locale }) => {
//   const lang = locale || defaultLocale
//   return {
//     props: {
//       ...(await serverSideTranslations(lang, ["common"])),
//     },
//   }
// }

export default Home
